// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExecutionRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ExecutionRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ExecutionFilter.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ExecutionRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ExecutionRequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ExecutionRequest_2eproto;
namespace protobuf {
class ExecutionRequest;
class ExecutionRequestDefaultTypeInternal;
extern ExecutionRequestDefaultTypeInternal _ExecutionRequest_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::ExecutionRequest* Arena::CreateMaybeMessage<::protobuf::ExecutionRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class ExecutionRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.ExecutionRequest) */ {
 public:
  inline ExecutionRequest() : ExecutionRequest(nullptr) {};
  virtual ~ExecutionRequest();

  ExecutionRequest(const ExecutionRequest& from);
  ExecutionRequest(ExecutionRequest&& from) noexcept
    : ExecutionRequest() {
    *this = ::std::move(from);
  }

  inline ExecutionRequest& operator=(const ExecutionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecutionRequest& operator=(ExecutionRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExecutionRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExecutionRequest* internal_default_instance() {
    return reinterpret_cast<const ExecutionRequest*>(
               &_ExecutionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ExecutionRequest& a, ExecutionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecutionRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecutionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExecutionRequest* New() const final {
    return CreateMaybeMessage<ExecutionRequest>(nullptr);
  }

  ExecutionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExecutionRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExecutionRequest& from);
  void MergeFrom(const ExecutionRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecutionRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.ExecutionRequest";
  }
  protected:
  explicit ExecutionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ExecutionRequest_2eproto);
    return ::descriptor_table_ExecutionRequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExecutionFilterFieldNumber = 2,
    kReqIdFieldNumber = 1,
  };
  // .protobuf.ExecutionFilter executionFilter = 2;
  bool has_executionfilter() const;
  private:
  bool _internal_has_executionfilter() const;
  public:
  void clear_executionfilter();
  const ::protobuf::ExecutionFilter& executionfilter() const;
  ::protobuf::ExecutionFilter* release_executionfilter();
  ::protobuf::ExecutionFilter* mutable_executionfilter();
  void set_allocated_executionfilter(::protobuf::ExecutionFilter* executionfilter);
  private:
  const ::protobuf::ExecutionFilter& _internal_executionfilter() const;
  ::protobuf::ExecutionFilter* _internal_mutable_executionfilter();
  public:
  void unsafe_arena_set_allocated_executionfilter(
      ::protobuf::ExecutionFilter* executionfilter);
  ::protobuf::ExecutionFilter* unsafe_arena_release_executionfilter();

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.ExecutionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::protobuf::ExecutionFilter* executionfilter_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  friend struct ::TableStruct_ExecutionRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ExecutionRequest

// int32 reqId = 1;
inline bool ExecutionRequest::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ExecutionRequest::has_reqid() const {
  return _internal_has_reqid();
}
inline void ExecutionRequest::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ExecutionRequest::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ExecutionRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionRequest.reqId)
  return _internal_reqid();
}
inline void ExecutionRequest::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  reqid_ = value;
}
inline void ExecutionRequest::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.ExecutionRequest.reqId)
}

// .protobuf.ExecutionFilter executionFilter = 2;
inline bool ExecutionRequest::_internal_has_executionfilter() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || executionfilter_ != nullptr);
  return value;
}
inline bool ExecutionRequest::has_executionfilter() const {
  return _internal_has_executionfilter();
}
inline const ::protobuf::ExecutionFilter& ExecutionRequest::_internal_executionfilter() const {
  const ::protobuf::ExecutionFilter* p = executionfilter_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf::ExecutionFilter*>(
      &::protobuf::_ExecutionFilter_default_instance_);
}
inline const ::protobuf::ExecutionFilter& ExecutionRequest::executionfilter() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionRequest.executionFilter)
  return _internal_executionfilter();
}
inline void ExecutionRequest::unsafe_arena_set_allocated_executionfilter(
    ::protobuf::ExecutionFilter* executionfilter) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(executionfilter_);
  }
  executionfilter_ = executionfilter;
  if (executionfilter) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ExecutionRequest.executionFilter)
}
inline ::protobuf::ExecutionFilter* ExecutionRequest::release_executionfilter() {
  auto temp = unsafe_arena_release_executionfilter();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protobuf::ExecutionFilter* ExecutionRequest::unsafe_arena_release_executionfilter() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionRequest.executionFilter)
  _has_bits_[0] &= ~0x00000001u;
  ::protobuf::ExecutionFilter* temp = executionfilter_;
  executionfilter_ = nullptr;
  return temp;
}
inline ::protobuf::ExecutionFilter* ExecutionRequest::_internal_mutable_executionfilter() {
  _has_bits_[0] |= 0x00000001u;
  if (executionfilter_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::ExecutionFilter>(GetArena());
    executionfilter_ = p;
  }
  return executionfilter_;
}
inline ::protobuf::ExecutionFilter* ExecutionRequest::mutable_executionfilter() {
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionRequest.executionFilter)
  return _internal_mutable_executionfilter();
}
inline void ExecutionRequest::set_allocated_executionfilter(::protobuf::ExecutionFilter* executionfilter) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(executionfilter_);
  }
  if (executionfilter) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(executionfilter)->GetArena();
    if (message_arena != submessage_arena) {
      executionfilter = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, executionfilter, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  executionfilter_ = executionfilter;
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionRequest.executionFilter)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ExecutionRequest_2eproto
