// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GlobalCancelRequest.proto
// Protobuf Java Version: 4.29.3

package com.ib.client.protobuf;

public final class GlobalCancelRequestProto {
  private GlobalCancelRequestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      GlobalCancelRequestProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GlobalCancelRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.GlobalCancelRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     * @return Whether the orderCancel field is set.
     */
    boolean hasOrderCancel();
    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     * @return The orderCancel.
     */
    com.ib.client.protobuf.OrderCancelProto.OrderCancel getOrderCancel();
    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     */
    com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder getOrderCancelOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.GlobalCancelRequest}
   */
  public static final class GlobalCancelRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.GlobalCancelRequest)
      GlobalCancelRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        GlobalCancelRequest.class.getName());
    }
    // Use GlobalCancelRequest.newBuilder() to construct.
    private GlobalCancelRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GlobalCancelRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ib.client.protobuf.GlobalCancelRequestProto.internal_static_protobuf_GlobalCancelRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ib.client.protobuf.GlobalCancelRequestProto.internal_static_protobuf_GlobalCancelRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.class, com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ORDERCANCEL_FIELD_NUMBER = 1;
    private com.ib.client.protobuf.OrderCancelProto.OrderCancel orderCancel_;
    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     * @return Whether the orderCancel field is set.
     */
    @java.lang.Override
    public boolean hasOrderCancel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     * @return The orderCancel.
     */
    @java.lang.Override
    public com.ib.client.protobuf.OrderCancelProto.OrderCancel getOrderCancel() {
      return orderCancel_ == null ? com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance() : orderCancel_;
    }
    /**
     * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
     */
    @java.lang.Override
    public com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder getOrderCancelOrBuilder() {
      return orderCancel_ == null ? com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance() : orderCancel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getOrderCancel());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOrderCancel());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest)) {
        return super.equals(obj);
      }
      com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest other = (com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest) obj;

      if (hasOrderCancel() != other.hasOrderCancel()) return false;
      if (hasOrderCancel()) {
        if (!getOrderCancel()
            .equals(other.getOrderCancel())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrderCancel()) {
        hash = (37 * hash) + ORDERCANCEL_FIELD_NUMBER;
        hash = (53 * hash) + getOrderCancel().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.GlobalCancelRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.GlobalCancelRequest)
        com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ib.client.protobuf.GlobalCancelRequestProto.internal_static_protobuf_GlobalCancelRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ib.client.protobuf.GlobalCancelRequestProto.internal_static_protobuf_GlobalCancelRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.class, com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.Builder.class);
      }

      // Construct using com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getOrderCancelFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        orderCancel_ = null;
        if (orderCancelBuilder_ != null) {
          orderCancelBuilder_.dispose();
          orderCancelBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ib.client.protobuf.GlobalCancelRequestProto.internal_static_protobuf_GlobalCancelRequest_descriptor;
      }

      @java.lang.Override
      public com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest getDefaultInstanceForType() {
        return com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest build() {
        com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest buildPartial() {
        com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest result = new com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.orderCancel_ = orderCancelBuilder_ == null
              ? orderCancel_
              : orderCancelBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest) {
          return mergeFrom((com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest other) {
        if (other == com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest.getDefaultInstance()) return this;
        if (other.hasOrderCancel()) {
          mergeOrderCancel(other.getOrderCancel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getOrderCancelFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.ib.client.protobuf.OrderCancelProto.OrderCancel orderCancel_;
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.OrderCancelProto.OrderCancel, com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder, com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder> orderCancelBuilder_;
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       * @return Whether the orderCancel field is set.
       */
      public boolean hasOrderCancel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       * @return The orderCancel.
       */
      public com.ib.client.protobuf.OrderCancelProto.OrderCancel getOrderCancel() {
        if (orderCancelBuilder_ == null) {
          return orderCancel_ == null ? com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance() : orderCancel_;
        } else {
          return orderCancelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public Builder setOrderCancel(com.ib.client.protobuf.OrderCancelProto.OrderCancel value) {
        if (orderCancelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderCancel_ = value;
        } else {
          orderCancelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public Builder setOrderCancel(
          com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder builderForValue) {
        if (orderCancelBuilder_ == null) {
          orderCancel_ = builderForValue.build();
        } else {
          orderCancelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public Builder mergeOrderCancel(com.ib.client.protobuf.OrderCancelProto.OrderCancel value) {
        if (orderCancelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            orderCancel_ != null &&
            orderCancel_ != com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance()) {
            getOrderCancelBuilder().mergeFrom(value);
          } else {
            orderCancel_ = value;
          }
        } else {
          orderCancelBuilder_.mergeFrom(value);
        }
        if (orderCancel_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public Builder clearOrderCancel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderCancel_ = null;
        if (orderCancelBuilder_ != null) {
          orderCancelBuilder_.dispose();
          orderCancelBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder getOrderCancelBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOrderCancelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      public com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder getOrderCancelOrBuilder() {
        if (orderCancelBuilder_ != null) {
          return orderCancelBuilder_.getMessageOrBuilder();
        } else {
          return orderCancel_ == null ?
              com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance() : orderCancel_;
        }
      }
      /**
       * <code>optional .protobuf.OrderCancel orderCancel = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.OrderCancelProto.OrderCancel, com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder, com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder> 
          getOrderCancelFieldBuilder() {
        if (orderCancelBuilder_ == null) {
          orderCancelBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ib.client.protobuf.OrderCancelProto.OrderCancel, com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder, com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder>(
                  getOrderCancel(),
                  getParentForChildren(),
                  isClean());
          orderCancel_ = null;
        }
        return orderCancelBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.GlobalCancelRequest)
    }

    // @@protoc_insertion_point(class_scope:protobuf.GlobalCancelRequest)
    private static final com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest();
    }

    public static com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GlobalCancelRequest>
        PARSER = new com.google.protobuf.AbstractParser<GlobalCancelRequest>() {
      @java.lang.Override
      public GlobalCancelRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GlobalCancelRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalCancelRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ib.client.protobuf.GlobalCancelRequestProto.GlobalCancelRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_GlobalCancelRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_GlobalCancelRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031GlobalCancelRequest.proto\022\010protobuf\032\021O" +
      "rderCancel.proto\"V\n\023GlobalCancelRequest\022" +
      "/\n\013orderCancel\030\001 \001(\0132\025.protobuf.OrderCan" +
      "celH\000\210\001\001B\016\n\014_orderCancelBC\n\026com.ib.clien" +
      "t.protobufB\030GlobalCancelRequestProto\252\002\016I" +
      "BApi.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ib.client.protobuf.OrderCancelProto.getDescriptor(),
        });
    internal_static_protobuf_GlobalCancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_GlobalCancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_GlobalCancelRequest_descriptor,
        new java.lang.String[] { "OrderCancel", });
    descriptor.resolveAllFeaturesImmutable();
    com.ib.client.protobuf.OrderCancelProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
