// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: OrderCancel.proto
// Protobuf Java Version: 4.29.3

package com.ib.client.protobuf;

public final class OrderCancelProto {
  private OrderCancelProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      OrderCancelProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderCancelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.OrderCancel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return Whether the manualOrderCancelTime field is set.
     */
    boolean hasManualOrderCancelTime();
    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return The manualOrderCancelTime.
     */
    java.lang.String getManualOrderCancelTime();
    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return The bytes for manualOrderCancelTime.
     */
    com.google.protobuf.ByteString
        getManualOrderCancelTimeBytes();

    /**
     * <code>optional string extOperator = 2;</code>
     * @return Whether the extOperator field is set.
     */
    boolean hasExtOperator();
    /**
     * <code>optional string extOperator = 2;</code>
     * @return The extOperator.
     */
    java.lang.String getExtOperator();
    /**
     * <code>optional string extOperator = 2;</code>
     * @return The bytes for extOperator.
     */
    com.google.protobuf.ByteString
        getExtOperatorBytes();

    /**
     * <code>optional int32 manualOrderIndicator = 3;</code>
     * @return Whether the manualOrderIndicator field is set.
     */
    boolean hasManualOrderIndicator();
    /**
     * <code>optional int32 manualOrderIndicator = 3;</code>
     * @return The manualOrderIndicator.
     */
    int getManualOrderIndicator();
  }
  /**
   * Protobuf type {@code protobuf.OrderCancel}
   */
  public static final class OrderCancel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.OrderCancel)
      OrderCancelOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        OrderCancel.class.getName());
    }
    // Use OrderCancel.newBuilder() to construct.
    private OrderCancel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OrderCancel() {
      manualOrderCancelTime_ = "";
      extOperator_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ib.client.protobuf.OrderCancelProto.internal_static_protobuf_OrderCancel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ib.client.protobuf.OrderCancelProto.internal_static_protobuf_OrderCancel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ib.client.protobuf.OrderCancelProto.OrderCancel.class, com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder.class);
    }

    private int bitField0_;
    public static final int MANUALORDERCANCELTIME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object manualOrderCancelTime_ = "";
    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return Whether the manualOrderCancelTime field is set.
     */
    @java.lang.Override
    public boolean hasManualOrderCancelTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return The manualOrderCancelTime.
     */
    @java.lang.Override
    public java.lang.String getManualOrderCancelTime() {
      java.lang.Object ref = manualOrderCancelTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manualOrderCancelTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string manualOrderCancelTime = 1;</code>
     * @return The bytes for manualOrderCancelTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getManualOrderCancelTimeBytes() {
      java.lang.Object ref = manualOrderCancelTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manualOrderCancelTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTOPERATOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object extOperator_ = "";
    /**
     * <code>optional string extOperator = 2;</code>
     * @return Whether the extOperator field is set.
     */
    @java.lang.Override
    public boolean hasExtOperator() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string extOperator = 2;</code>
     * @return The extOperator.
     */
    @java.lang.Override
    public java.lang.String getExtOperator() {
      java.lang.Object ref = extOperator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extOperator_ = s;
        return s;
      }
    }
    /**
     * <code>optional string extOperator = 2;</code>
     * @return The bytes for extOperator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtOperatorBytes() {
      java.lang.Object ref = extOperator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extOperator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANUALORDERINDICATOR_FIELD_NUMBER = 3;
    private int manualOrderIndicator_ = 0;
    /**
     * <code>optional int32 manualOrderIndicator = 3;</code>
     * @return Whether the manualOrderIndicator field is set.
     */
    @java.lang.Override
    public boolean hasManualOrderIndicator() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 manualOrderIndicator = 3;</code>
     * @return The manualOrderIndicator.
     */
    @java.lang.Override
    public int getManualOrderIndicator() {
      return manualOrderIndicator_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, manualOrderCancelTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, extOperator_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, manualOrderIndicator_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, manualOrderCancelTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, extOperator_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, manualOrderIndicator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ib.client.protobuf.OrderCancelProto.OrderCancel)) {
        return super.equals(obj);
      }
      com.ib.client.protobuf.OrderCancelProto.OrderCancel other = (com.ib.client.protobuf.OrderCancelProto.OrderCancel) obj;

      if (hasManualOrderCancelTime() != other.hasManualOrderCancelTime()) return false;
      if (hasManualOrderCancelTime()) {
        if (!getManualOrderCancelTime()
            .equals(other.getManualOrderCancelTime())) return false;
      }
      if (hasExtOperator() != other.hasExtOperator()) return false;
      if (hasExtOperator()) {
        if (!getExtOperator()
            .equals(other.getExtOperator())) return false;
      }
      if (hasManualOrderIndicator() != other.hasManualOrderIndicator()) return false;
      if (hasManualOrderIndicator()) {
        if (getManualOrderIndicator()
            != other.getManualOrderIndicator()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasManualOrderCancelTime()) {
        hash = (37 * hash) + MANUALORDERCANCELTIME_FIELD_NUMBER;
        hash = (53 * hash) + getManualOrderCancelTime().hashCode();
      }
      if (hasExtOperator()) {
        hash = (37 * hash) + EXTOPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + getExtOperator().hashCode();
      }
      if (hasManualOrderIndicator()) {
        hash = (37 * hash) + MANUALORDERINDICATOR_FIELD_NUMBER;
        hash = (53 * hash) + getManualOrderIndicator();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ib.client.protobuf.OrderCancelProto.OrderCancel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.OrderCancel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.OrderCancel)
        com.ib.client.protobuf.OrderCancelProto.OrderCancelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ib.client.protobuf.OrderCancelProto.internal_static_protobuf_OrderCancel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ib.client.protobuf.OrderCancelProto.internal_static_protobuf_OrderCancel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ib.client.protobuf.OrderCancelProto.OrderCancel.class, com.ib.client.protobuf.OrderCancelProto.OrderCancel.Builder.class);
      }

      // Construct using com.ib.client.protobuf.OrderCancelProto.OrderCancel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        manualOrderCancelTime_ = "";
        extOperator_ = "";
        manualOrderIndicator_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ib.client.protobuf.OrderCancelProto.internal_static_protobuf_OrderCancel_descriptor;
      }

      @java.lang.Override
      public com.ib.client.protobuf.OrderCancelProto.OrderCancel getDefaultInstanceForType() {
        return com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance();
      }

      @java.lang.Override
      public com.ib.client.protobuf.OrderCancelProto.OrderCancel build() {
        com.ib.client.protobuf.OrderCancelProto.OrderCancel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ib.client.protobuf.OrderCancelProto.OrderCancel buildPartial() {
        com.ib.client.protobuf.OrderCancelProto.OrderCancel result = new com.ib.client.protobuf.OrderCancelProto.OrderCancel(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ib.client.protobuf.OrderCancelProto.OrderCancel result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.manualOrderCancelTime_ = manualOrderCancelTime_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.extOperator_ = extOperator_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.manualOrderIndicator_ = manualOrderIndicator_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ib.client.protobuf.OrderCancelProto.OrderCancel) {
          return mergeFrom((com.ib.client.protobuf.OrderCancelProto.OrderCancel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ib.client.protobuf.OrderCancelProto.OrderCancel other) {
        if (other == com.ib.client.protobuf.OrderCancelProto.OrderCancel.getDefaultInstance()) return this;
        if (other.hasManualOrderCancelTime()) {
          manualOrderCancelTime_ = other.manualOrderCancelTime_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasExtOperator()) {
          extOperator_ = other.extOperator_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasManualOrderIndicator()) {
          setManualOrderIndicator(other.getManualOrderIndicator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                manualOrderCancelTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                extOperator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                manualOrderIndicator_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object manualOrderCancelTime_ = "";
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @return Whether the manualOrderCancelTime field is set.
       */
      public boolean hasManualOrderCancelTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @return The manualOrderCancelTime.
       */
      public java.lang.String getManualOrderCancelTime() {
        java.lang.Object ref = manualOrderCancelTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manualOrderCancelTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @return The bytes for manualOrderCancelTime.
       */
      public com.google.protobuf.ByteString
          getManualOrderCancelTimeBytes() {
        java.lang.Object ref = manualOrderCancelTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manualOrderCancelTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @param value The manualOrderCancelTime to set.
       * @return This builder for chaining.
       */
      public Builder setManualOrderCancelTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        manualOrderCancelTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearManualOrderCancelTime() {
        manualOrderCancelTime_ = getDefaultInstance().getManualOrderCancelTime();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string manualOrderCancelTime = 1;</code>
       * @param value The bytes for manualOrderCancelTime to set.
       * @return This builder for chaining.
       */
      public Builder setManualOrderCancelTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        manualOrderCancelTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object extOperator_ = "";
      /**
       * <code>optional string extOperator = 2;</code>
       * @return Whether the extOperator field is set.
       */
      public boolean hasExtOperator() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string extOperator = 2;</code>
       * @return The extOperator.
       */
      public java.lang.String getExtOperator() {
        java.lang.Object ref = extOperator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extOperator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extOperator = 2;</code>
       * @return The bytes for extOperator.
       */
      public com.google.protobuf.ByteString
          getExtOperatorBytes() {
        java.lang.Object ref = extOperator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extOperator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extOperator = 2;</code>
       * @param value The extOperator to set.
       * @return This builder for chaining.
       */
      public Builder setExtOperator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        extOperator_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extOperator = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtOperator() {
        extOperator_ = getDefaultInstance().getExtOperator();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string extOperator = 2;</code>
       * @param value The bytes for extOperator to set.
       * @return This builder for chaining.
       */
      public Builder setExtOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        extOperator_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int manualOrderIndicator_ ;
      /**
       * <code>optional int32 manualOrderIndicator = 3;</code>
       * @return Whether the manualOrderIndicator field is set.
       */
      @java.lang.Override
      public boolean hasManualOrderIndicator() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 manualOrderIndicator = 3;</code>
       * @return The manualOrderIndicator.
       */
      @java.lang.Override
      public int getManualOrderIndicator() {
        return manualOrderIndicator_;
      }
      /**
       * <code>optional int32 manualOrderIndicator = 3;</code>
       * @param value The manualOrderIndicator to set.
       * @return This builder for chaining.
       */
      public Builder setManualOrderIndicator(int value) {

        manualOrderIndicator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 manualOrderIndicator = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearManualOrderIndicator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        manualOrderIndicator_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.OrderCancel)
    }

    // @@protoc_insertion_point(class_scope:protobuf.OrderCancel)
    private static final com.ib.client.protobuf.OrderCancelProto.OrderCancel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ib.client.protobuf.OrderCancelProto.OrderCancel();
    }

    public static com.ib.client.protobuf.OrderCancelProto.OrderCancel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderCancel>
        PARSER = new com.google.protobuf.AbstractParser<OrderCancel>() {
      @java.lang.Override
      public OrderCancel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrderCancel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderCancel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ib.client.protobuf.OrderCancelProto.OrderCancel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OrderCancel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OrderCancel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021OrderCancel.proto\022\010protobuf\"\261\001\n\013OrderC" +
      "ancel\022\"\n\025manualOrderCancelTime\030\001 \001(\tH\000\210\001" +
      "\001\022\030\n\013extOperator\030\002 \001(\tH\001\210\001\001\022!\n\024manualOrd" +
      "erIndicator\030\003 \001(\005H\002\210\001\001B\030\n\026_manualOrderCa" +
      "ncelTimeB\016\n\014_extOperatorB\027\n\025_manualOrder" +
      "IndicatorB;\n\026com.ib.client.protobufB\020Ord" +
      "erCancelProto\252\002\016IBApi.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_OrderCancel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_OrderCancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_OrderCancel_descriptor,
        new java.lang.String[] { "ManualOrderCancelTime", "ExtOperator", "ManualOrderIndicator", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
