// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PlaceOrderRequest.proto
// Protobuf Java Version: 4.29.3

package com.ib.client.protobuf;

public final class PlaceOrderRequestProto {
  private PlaceOrderRequestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PlaceOrderRequestProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlaceOrderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PlaceOrderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 orderId = 1;</code>
     * @return Whether the orderId field is set.
     */
    boolean hasOrderId();
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return The orderId.
     */
    int getOrderId();

    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     * @return Whether the contract field is set.
     */
    boolean hasContract();
    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     * @return The contract.
     */
    com.ib.client.protobuf.ContractProto.Contract getContract();
    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     */
    com.ib.client.protobuf.ContractProto.ContractOrBuilder getContractOrBuilder();

    /**
     * <code>optional .protobuf.Order order = 3;</code>
     * @return Whether the order field is set.
     */
    boolean hasOrder();
    /**
     * <code>optional .protobuf.Order order = 3;</code>
     * @return The order.
     */
    com.ib.client.protobuf.OrderProto.Order getOrder();
    /**
     * <code>optional .protobuf.Order order = 3;</code>
     */
    com.ib.client.protobuf.OrderProto.OrderOrBuilder getOrderOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.PlaceOrderRequest}
   */
  public static final class PlaceOrderRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.PlaceOrderRequest)
      PlaceOrderRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        PlaceOrderRequest.class.getName());
    }
    // Use PlaceOrderRequest.newBuilder() to construct.
    private PlaceOrderRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlaceOrderRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ib.client.protobuf.PlaceOrderRequestProto.internal_static_protobuf_PlaceOrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ib.client.protobuf.PlaceOrderRequestProto.internal_static_protobuf_PlaceOrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.class, com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ORDERID_FIELD_NUMBER = 1;
    private int orderId_ = 0;
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return Whether the orderId field is set.
     */
    @java.lang.Override
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 orderId = 1;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public int getOrderId() {
      return orderId_;
    }

    public static final int CONTRACT_FIELD_NUMBER = 2;
    private com.ib.client.protobuf.ContractProto.Contract contract_;
    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     * @return Whether the contract field is set.
     */
    @java.lang.Override
    public boolean hasContract() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     * @return The contract.
     */
    @java.lang.Override
    public com.ib.client.protobuf.ContractProto.Contract getContract() {
      return contract_ == null ? com.ib.client.protobuf.ContractProto.Contract.getDefaultInstance() : contract_;
    }
    /**
     * <code>optional .protobuf.Contract contract = 2;</code>
     */
    @java.lang.Override
    public com.ib.client.protobuf.ContractProto.ContractOrBuilder getContractOrBuilder() {
      return contract_ == null ? com.ib.client.protobuf.ContractProto.Contract.getDefaultInstance() : contract_;
    }

    public static final int ORDER_FIELD_NUMBER = 3;
    private com.ib.client.protobuf.OrderProto.Order order_;
    /**
     * <code>optional .protobuf.Order order = 3;</code>
     * @return Whether the order field is set.
     */
    @java.lang.Override
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .protobuf.Order order = 3;</code>
     * @return The order.
     */
    @java.lang.Override
    public com.ib.client.protobuf.OrderProto.Order getOrder() {
      return order_ == null ? com.ib.client.protobuf.OrderProto.Order.getDefaultInstance() : order_;
    }
    /**
     * <code>optional .protobuf.Order order = 3;</code>
     */
    @java.lang.Override
    public com.ib.client.protobuf.OrderProto.OrderOrBuilder getOrderOrBuilder() {
      return order_ == null ? com.ib.client.protobuf.OrderProto.Order.getDefaultInstance() : order_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, orderId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getContract());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getOrder());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContract());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOrder());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest)) {
        return super.equals(obj);
      }
      com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest other = (com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest) obj;

      if (hasOrderId() != other.hasOrderId()) return false;
      if (hasOrderId()) {
        if (getOrderId()
            != other.getOrderId()) return false;
      }
      if (hasContract() != other.hasContract()) return false;
      if (hasContract()) {
        if (!getContract()
            .equals(other.getContract())) return false;
      }
      if (hasOrder() != other.hasOrder()) return false;
      if (hasOrder()) {
        if (!getOrder()
            .equals(other.getOrder())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrderId()) {
        hash = (37 * hash) + ORDERID_FIELD_NUMBER;
        hash = (53 * hash) + getOrderId();
      }
      if (hasContract()) {
        hash = (37 * hash) + CONTRACT_FIELD_NUMBER;
        hash = (53 * hash) + getContract().hashCode();
      }
      if (hasOrder()) {
        hash = (37 * hash) + ORDER_FIELD_NUMBER;
        hash = (53 * hash) + getOrder().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.PlaceOrderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PlaceOrderRequest)
        com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ib.client.protobuf.PlaceOrderRequestProto.internal_static_protobuf_PlaceOrderRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ib.client.protobuf.PlaceOrderRequestProto.internal_static_protobuf_PlaceOrderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.class, com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.Builder.class);
      }

      // Construct using com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getContractFieldBuilder();
          getOrderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        orderId_ = 0;
        contract_ = null;
        if (contractBuilder_ != null) {
          contractBuilder_.dispose();
          contractBuilder_ = null;
        }
        order_ = null;
        if (orderBuilder_ != null) {
          orderBuilder_.dispose();
          orderBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ib.client.protobuf.PlaceOrderRequestProto.internal_static_protobuf_PlaceOrderRequest_descriptor;
      }

      @java.lang.Override
      public com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest getDefaultInstanceForType() {
        return com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest build() {
        com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest buildPartial() {
        com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest result = new com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.orderId_ = orderId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.contract_ = contractBuilder_ == null
              ? contract_
              : contractBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.order_ = orderBuilder_ == null
              ? order_
              : orderBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest) {
          return mergeFrom((com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest other) {
        if (other == com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasContract()) {
          mergeContract(other.getContract());
        }
        if (other.hasOrder()) {
          mergeOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                orderId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getContractFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getOrderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int orderId_ ;
      /**
       * <code>optional int32 orderId = 1;</code>
       * @return Whether the orderId field is set.
       */
      @java.lang.Override
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 orderId = 1;</code>
       * @return The orderId.
       */
      @java.lang.Override
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int32 orderId = 1;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(int value) {

        orderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 orderId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = 0;
        onChanged();
        return this;
      }

      private com.ib.client.protobuf.ContractProto.Contract contract_;
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.ContractProto.Contract, com.ib.client.protobuf.ContractProto.Contract.Builder, com.ib.client.protobuf.ContractProto.ContractOrBuilder> contractBuilder_;
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       * @return Whether the contract field is set.
       */
      public boolean hasContract() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       * @return The contract.
       */
      public com.ib.client.protobuf.ContractProto.Contract getContract() {
        if (contractBuilder_ == null) {
          return contract_ == null ? com.ib.client.protobuf.ContractProto.Contract.getDefaultInstance() : contract_;
        } else {
          return contractBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public Builder setContract(com.ib.client.protobuf.ContractProto.Contract value) {
        if (contractBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contract_ = value;
        } else {
          contractBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public Builder setContract(
          com.ib.client.protobuf.ContractProto.Contract.Builder builderForValue) {
        if (contractBuilder_ == null) {
          contract_ = builderForValue.build();
        } else {
          contractBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public Builder mergeContract(com.ib.client.protobuf.ContractProto.Contract value) {
        if (contractBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            contract_ != null &&
            contract_ != com.ib.client.protobuf.ContractProto.Contract.getDefaultInstance()) {
            getContractBuilder().mergeFrom(value);
          } else {
            contract_ = value;
          }
        } else {
          contractBuilder_.mergeFrom(value);
        }
        if (contract_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public Builder clearContract() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contract_ = null;
        if (contractBuilder_ != null) {
          contractBuilder_.dispose();
          contractBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public com.ib.client.protobuf.ContractProto.Contract.Builder getContractBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContractFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      public com.ib.client.protobuf.ContractProto.ContractOrBuilder getContractOrBuilder() {
        if (contractBuilder_ != null) {
          return contractBuilder_.getMessageOrBuilder();
        } else {
          return contract_ == null ?
              com.ib.client.protobuf.ContractProto.Contract.getDefaultInstance() : contract_;
        }
      }
      /**
       * <code>optional .protobuf.Contract contract = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.ContractProto.Contract, com.ib.client.protobuf.ContractProto.Contract.Builder, com.ib.client.protobuf.ContractProto.ContractOrBuilder> 
          getContractFieldBuilder() {
        if (contractBuilder_ == null) {
          contractBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ib.client.protobuf.ContractProto.Contract, com.ib.client.protobuf.ContractProto.Contract.Builder, com.ib.client.protobuf.ContractProto.ContractOrBuilder>(
                  getContract(),
                  getParentForChildren(),
                  isClean());
          contract_ = null;
        }
        return contractBuilder_;
      }

      private com.ib.client.protobuf.OrderProto.Order order_;
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.OrderProto.Order, com.ib.client.protobuf.OrderProto.Order.Builder, com.ib.client.protobuf.OrderProto.OrderOrBuilder> orderBuilder_;
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       * @return Whether the order field is set.
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       * @return The order.
       */
      public com.ib.client.protobuf.OrderProto.Order getOrder() {
        if (orderBuilder_ == null) {
          return order_ == null ? com.ib.client.protobuf.OrderProto.Order.getDefaultInstance() : order_;
        } else {
          return orderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public Builder setOrder(com.ib.client.protobuf.OrderProto.Order value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          order_ = value;
        } else {
          orderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public Builder setOrder(
          com.ib.client.protobuf.OrderProto.Order.Builder builderForValue) {
        if (orderBuilder_ == null) {
          order_ = builderForValue.build();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public Builder mergeOrder(com.ib.client.protobuf.OrderProto.Order value) {
        if (orderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            order_ != null &&
            order_ != com.ib.client.protobuf.OrderProto.Order.getDefaultInstance()) {
            getOrderBuilder().mergeFrom(value);
          } else {
            order_ = value;
          }
        } else {
          orderBuilder_.mergeFrom(value);
        }
        if (order_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        order_ = null;
        if (orderBuilder_ != null) {
          orderBuilder_.dispose();
          orderBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public com.ib.client.protobuf.OrderProto.Order.Builder getOrderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      public com.ib.client.protobuf.OrderProto.OrderOrBuilder getOrderOrBuilder() {
        if (orderBuilder_ != null) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          return order_ == null ?
              com.ib.client.protobuf.OrderProto.Order.getDefaultInstance() : order_;
        }
      }
      /**
       * <code>optional .protobuf.Order order = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ib.client.protobuf.OrderProto.Order, com.ib.client.protobuf.OrderProto.Order.Builder, com.ib.client.protobuf.OrderProto.OrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ib.client.protobuf.OrderProto.Order, com.ib.client.protobuf.OrderProto.Order.Builder, com.ib.client.protobuf.OrderProto.OrderOrBuilder>(
                  getOrder(),
                  getParentForChildren(),
                  isClean());
          order_ = null;
        }
        return orderBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.PlaceOrderRequest)
    }

    // @@protoc_insertion_point(class_scope:protobuf.PlaceOrderRequest)
    private static final com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest();
    }

    public static com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlaceOrderRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlaceOrderRequest>() {
      @java.lang.Override
      public PlaceOrderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlaceOrderRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaceOrderRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ib.client.protobuf.PlaceOrderRequestProto.PlaceOrderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PlaceOrderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_PlaceOrderRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027PlaceOrderRequest.proto\022\010protobuf\032\016Con" +
      "tract.proto\032\013Order.proto\"\234\001\n\021PlaceOrderR" +
      "equest\022\024\n\007orderId\030\001 \001(\005H\000\210\001\001\022)\n\010contract" +
      "\030\002 \001(\0132\022.protobuf.ContractH\001\210\001\001\022#\n\005order" +
      "\030\003 \001(\0132\017.protobuf.OrderH\002\210\001\001B\n\n\010_orderId" +
      "B\013\n\t_contractB\010\n\006_orderBA\n\026com.ib.client" +
      ".protobufB\026PlaceOrderRequestProto\252\002\016IBAp" +
      "i.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ib.client.protobuf.ContractProto.getDescriptor(),
          com.ib.client.protobuf.OrderProto.getDescriptor(),
        });
    internal_static_protobuf_PlaceOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_PlaceOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_PlaceOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", "Contract", "Order", });
    descriptor.resolveAllFeaturesImmutable();
    com.ib.client.protobuf.ContractProto.getDescriptor();
    com.ib.client.protobuf.OrderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
